### ISSUE TITLE
Incorrect progress bar outline / alerts / active chip / badges states on Style Guide web in Bootstrap

### ISSUE THREAD

**Issue by soniakaukonen** [trimble-oss/website-modus-bootstrap.trimble.com#274]
- [x] (Light mode) Badge Warning background color should be `#FBAD26`
- [x] Progress Bar border should be: `#6a6e79` (not `#8c8b96`)
- [x] chip-solid background color should be `#019aeb`
- [x] alert-dark border should be `#464B52`

_Issues originally reported at: https://github.com/trimble-oss/website-modus.trimble.com/issues/394_

Partial fix: https://bitbucket.trimble.tools/projects/TMDS/repos/modus-bootstrap/pull-requests/291/overview
