### ISSUE TITLE
Release Modus Bootstrap v1.5.6

### ISSUE THREAD

**Issue by coliff** [trimble-oss/website-modus-bootstrap.trimble.com#286]
- [x] [#285 Fix Shadow Color RGB Values](https://github.com/trimble-oss/website-modus-bootstrap.trimble.com/issues/285)
- [x] Fix for Breadcrumb Active color (Light mode) - is now `#252a2e` (was `#6c757d`)
- [x] Fix for Accordion Header color (light mode) https://bitbucket.trimble.tools/projects/TMDS/repos/modus-bootstrap/pull-requests/293/overview
- [x] Fix for chip-solid (Dark Mode) background color (is now `#019aeb`)
- [x] Fix for alert-dark (Dark Mode) border (is now `#464B52`)
- [x] Reduce custom control switch animation from .15s to .1s
